version: '3'

services:
  app:
    restart: always
    build:
      ./app
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      TZ: ${TZ:-Asia/Yekaterinburg}
      PRODUCTION: ${PRODUCTION:-Off}
      SITE_ID: ${SITE_ID:-1}
    volumes:
      - application:/var/www/html
      - static:/var/www/html/static
      - media:/var/www/html/media
    networks:
      - frontend
      - backend
    logging:
      driver: ${APP_LOG_DRIVER:-json-file}
      options:
        max-size: ${APP_LOG_MAX_SIZE:-2m}
        max-file: ${APP_LOG_MAX_FILE:-4}

  web:
    build: ./web
    restart: always
    depends_on:
      - app
    links:
      - app
    command: nginx -g 'daemon off;'
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      SSL_POLICY: ${SSL_POLICY:-Mozilla-Modern}
      TZ: ${TZ:-Asia/Yekaterinburg}
    volumes:
      - application:/var/www/html:ro
      - static:/var/www/html/static:ro
      - media:/var/www/html/media:ro
    networks:
      - frontend
    logging:
      driver: ${WEB_LOG_DRIVER:-json-file}
      options:
        max-size: ${WEB_LOG_MAX_SIZE:-2m}
        max-file: ${WEB_LOG_MAX_FILE:-4}

networks:
  frontend:
    external:
      name: ${NET_FRONTEND:-frontend}
  backend:
    external:
      name: ${NET_BACKEND:-backend}

volumes:
  application: {}
  static: {}
  media: {}
